-- MySQL Script generated by MySQL Workbench
-- Fri May 23 14:35:10 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema eknjiznica2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema eknjiznica2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eknjiznica2` DEFAULT CHARACTER SET utf8 ;
USE `eknjiznica2` ;

-- -----------------------------------------------------
-- Table `eknjiznica2`.`avtor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eknjiznica2`.`avtor` (
  `idAvtor` INT(11) NOT NULL AUTO_INCREMENT,
  `ime` VARCHAR(100) NOT NULL,
  `priimek` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idAvtor`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `eknjiznica2`.`clan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eknjiznica2`.`clan` (
  `idClan` INT(11) NOT NULL AUTO_INCREMENT,
  `uporabniskoIme` VARCHAR(50) NOT NULL,
  `geslo` VARCHAR(255) NOT NULL,
  `ime` VARCHAR(100) NOT NULL,
  `priimek` VARCHAR(100) NOT NULL,
  `naslov` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `izposoje` VARCHAR(20) NOT NULL,
  `clanarina` TINYINT(1) NOT NULL,
  `tipUporabnika` INT(11) NULL DEFAULT 0,
  PRIMARY KEY (`idClan`),
  UNIQUE INDEX `uporabniskoIme` (`uporabniskoIme` ASC) VISIBLE,
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `eknjiznica2`.`knjiznice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eknjiznica2`.`knjiznice` (
  `idKnjiznice` INT(11) NOT NULL AUTO_INCREMENT,
  `ime` VARCHAR(255) NOT NULL,
  `naslov` VARCHAR(255) NOT NULL,
  `telefon` VARCHAR(20) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `opis` VARCHAR(5000) NOT NULL,
  PRIMARY KEY (`idKnjiznice`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `eknjiznica2`.`gradiva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eknjiznica2`.`gradiva` (
  `idGradiva` INT(11) NOT NULL AUTO_INCREMENT,
  `ime` VARCHAR(255) NOT NULL,
  `tipGradiva` VARCHAR(100) NOT NULL,
  `idKnjiznice` INT(11) NOT NULL,
  `idZalozba` INT(11) NULL DEFAULT NULL,
  `idAvtor` INT(11) NULL DEFAULT NULL,
  `slika` VARCHAR(255) NULL DEFAULT NULL,
  `opis` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`idGradiva`),
  INDEX `idZalozba` (`idZalozba` ASC) VISIBLE,
  INDEX `idKnjiznice` (`idKnjiznice` ASC) VISIBLE,
  INDEX `idAvtor` (`idAvtor` ASC) VISIBLE,
  CONSTRAINT `gradiva_ibfk_1`
    FOREIGN KEY (`idZalozba`)
    REFERENCES `eknjiznica2`.`clan` (`idClan`),
  CONSTRAINT `gradiva_ibfk_2`
    FOREIGN KEY (`idKnjiznice`)
    REFERENCES `eknjiznica2`.`knjiznice` (`idKnjiznice`),
  CONSTRAINT `gradiva_ibfk_3`
    FOREIGN KEY (`idAvtor`)
    REFERENCES `eknjiznica2`.`avtor` (`idAvtor`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `eknjiznica2`.`izposoja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eknjiznica2`.`izposoja` (
  `idIzposoja` INT(11) NOT NULL AUTO_INCREMENT,
  `idClan` INT(11) NOT NULL,
  `idGradiva` INT(11) NOT NULL,
  `datumIzposoje` DATE NOT NULL,
  `datumVracila` DATE NULL DEFAULT NULL,
  `idKnjiznicarja` INT(11) NOT NULL,
  PRIMARY KEY (`idIzposoja`),
  INDEX `idClan` (`idClan` ASC) VISIBLE,
  INDEX `idGradiva` (`idGradiva` ASC) VISIBLE,
  INDEX `izposoja_ibfk_3` (`idKnjiznicarja` ASC) VISIBLE,
  CONSTRAINT `izposoja_ibfk_1`
    FOREIGN KEY (`idClan`)
    REFERENCES `eknjiznica2`.`clan` (`idClan`),
  CONSTRAINT `izposoja_ibfk_2`
    FOREIGN KEY (`idGradiva`)
    REFERENCES `eknjiznica2`.`gradiva` (`idGradiva`),
  CONSTRAINT `izposoja_ibfk_3`
    FOREIGN KEY (`idKnjiznicarja`)
    REFERENCES `eknjiznica2`.`clan` (`idClan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `eknjiznica2`.`razpolozljivost`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eknjiznica2`.`razpolozljivost` (
  `idGradiva` INT(11) NOT NULL,
  `idKnjiznice` INT(11) NOT NULL,
  `status` VARCHAR(20) NOT NULL,
  `steviloGradiv` INT(11) NOT NULL,
  `steviloIzposojenih` INT(11) NOT NULL,
  `steviloRezerviranih` INT(11) NOT NULL,
  PRIMARY KEY (`idGradiva`, `idKnjiznice`),
  INDEX `idKnjiznice` (`idKnjiznice` ASC) VISIBLE,
  CONSTRAINT `razpolozljivost_ibfk_1`
    FOREIGN KEY (`idGradiva`)
    REFERENCES `eknjiznica2`.`gradiva` (`idGradiva`),
  CONSTRAINT `razpolozljivost_ibfk_2`
    FOREIGN KEY (`idKnjiznice`)
    REFERENCES `eknjiznica2`.`knjiznice` (`idKnjiznice`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
